### ISSUE TITLE
One dependency causes multiple PRs

### ISSUE THREAD

**Issue by wowselim** [DanySK/upgradle#60]
Hey, thanks for this project! I have tried it on [one of my own repos](https://github.com/wowselim/hsl-image/pulls) and observed a weird behavior:

upgradle created multiple PRs for the same dependency. It started with the latest version for the gradle wrapper, then proceeded to create PRs for every other version between the current and the latest (at least that what I assume. I killed the process once I realized.

**Comment by DanySK** [comment]
Yes, this is the behaviour of the current module for upgrading the wrapper.
The rationale behind it is: if your project is connected to the CI, you will get update proposals from the most recent the oldest, and you will get green-flagged as soon as the most recent update succeeds.

To enrich/select the behaviour, we'd need a way to pass down options to modules (or write other modules that only propose upgrades to the next / next stable / latest / latest stable).

**Comment by wowselim** [comment]
That makes sense! I think it would be beneficial to be able to control this behavior:
```
14:42:48.853 [main] INFO  o.d.upgradle.modules.GradleWrapper - Gradle can be updated to: [6.4-rc-1, 6.3, 6.3-rc-4, 6.3-rc-3, 6.3-rc-2, 6.3-rc-1, 6.2.2, 6.2.1, 6.2, 6.2-rc-3, 6.2-rc-2, 6.2-rc-1, 6.1.1, 6.1, 6.1-rc-3, 6.1-rc-2, 6.1-rc-1, 6.0.1, 6.0, 6.0-rc-3, 6.0-rc-2, 6.0-rc-1, 5.6.4, 5.6.3, 5.6.2, 5.6.1, 5.6, 5.6-rc-2, 5.6-rc-1, 5.5.1, 5.5, 5.5-rc-4, 5.5-rc-3, 5.5-rc-2, 5.5-rc-1, 5.4.1, 5.4, 5.4-rc-1, 5.3.1, 5.3, 5.3-rc-3, 5.3-rc-2, 5.3-rc-1, 5.2.1, 5.2, 5.2-rc-1, 5.1.1, 5.1, 5.1-rc-3, 5.1-rc-2, 5.1-rc-1, 5.0, 5.0-rc-5, 5.0-rc-4, 5.0-rc-3, 5.0-rc-2, 5.0-rc-1, 4.10.3, 4.10.2, 4.10.1, 4.10, 4.10-rc-3, 4.10-rc-2, 4.10-rc-1, 4.9, 4.9-rc-2, 4.9-rc-1, 4.8.1, 4.8, 4.8-rc-3, 4.8-rc-2, 4.8-rc-1, 4.7, 4.7-rc-2, 4.7-rc-1, 4.6, 4.6-rc-2, 4.6-rc-1, 4.5.1, 4.5, 4.5-rc-2, 4.5-rc-1, 4.4.1]
```

This is a lot of PRs for just one dependency. In my case it would be enough if it opened a PR for the latest version (even if that's broken). At least I'll know that the dependency is outdated.

**Comment by DanySK** [comment]
I thought about this, and I think that the behavior must be configured, and probably the "generate all updates" should be a fallback strategy, not the default. It's infact a PITA for those adopting upgradle and having many repos not updated.

**Comment by DanySK** [comment]
The latest beta supports different update strategies, and filters versions by regex. Once tested, I'll update the guide and close this bug.

**Comment by DanySK** [comment]
0.3.0 released, and configuration explained. Closing!
