### ISSUE TITLE
DanySK is co-author for every PR

### ISSUE THREAD

**Issue by wowselim** [DanySK/upgradle#61]
For this issue I don't really know why this happens or whether this is a problem at all but all PRs that are created are co-authored by DanySK: https://github.com/wowselim/hsl-image/pull/21
I just think it's weird :smile:

**Comment by wowselim** [comment]
https://github.com/DanySK/upgradle/blob/master/src/main/kotlin/org/danilopianini/upgradle/Git.kt#L40

This might be the cause of it

**Comment by DanySK** [comment]
Ugh, this looks like something I used for development and never added a way to control via configuration.
There should definitely be a way to configure who's making the PR.

Would a section in the YAML configuration address the issue for your use case? Something like
```yaml
include:
...
author: your.email@foo.bar
```

**Comment by wowselim** [comment]
That sounds reasonable :smile: Maybe for the future, create a github account for upgradle and use that email as a default? I think that would be less confusing! I can work on a PR if you like.

**Comment by DanySK** [comment]
It may make sense, yet it should be possible to customize the committer of the changes.
Something like:
```yaml
authorship:
  name: Foo Bar
  email: foo.bar@foobar.baz
```
in the config file, defaulting to the current values if omitted.

PRs are welcome

**Comment by DanySK** [comment]
@jckoenen, your change should get published shortly on the releases page. Give it a spin if you can, once it got at least one run and documentation is up to date I'll release 0.1.15

**Comment by jckoenen** [comment]
@DanySK Great, thanks - I'll try later today. 
To be honest, I haven't actually used this project yet, but this issue was a prerequisite to me. I'll ping you when I have tried it.
