### ISSUE TITLE
Filter repositories by topics

### ISSUE THREAD

**Issue by jckoenen** [DanySK/upgradle#88]
Hi!

Adding the possibility to discover repositories via [github topics](https://help.github.com/en/github/searching-for-information-on-github/searching-for-repositories#search-by-topic) would provide a nice way to enable an 'opt-in' mechanism for repositories.

In my usecase, I'd like to run upgradle on some scheduled container, for the whole organisation. Including or removing some repository should not require a change to the deployment of that container, instead enabling each repository owner to opt in for updates.
In this scenario, it's not really feasible to run on any predefined names (and especially not on _all_ repository), but making use of topics makes it easy to include a new repo.

Let me know what you think of this. Of course I'd also volunteer to build it ;)

Cheers,
Joe

**Comment by DanySK** [comment]
Uh! This is nice!
I did not even know about topics. We could add a "topics" key for both inclusion and exclusion

**Comment by jckoenen** [comment]
Yeah, sounds good. I think I'll find enough time for that over the weekend, else I be in touch :D

**Comment by DanySK** [comment]
Grand, thanks

**Comment by DanySK** [comment]
Topics are now supported, closing
